set_project("xmake-example")
set_languages("c++17")
add_rules("mode.debug", "mode.release")
add_requires("tbox master", {debug = true})
-- cmake packages
add_requires("cmake::OpenCV", {alias = "opencv",system = true})

target("yolov5")
    set_kind("binary")
    add_files("src/yolo/*.cpp")
    add_includedirs("include")
    add_includedirs("3rdparty/onnxruntime-linux-x64-gpu-1.12.1/include")
    add_links("onnxruntime")
    add_linkdirs("3rdparty/onnxruntime-linux-x64-gpu-1.12.1/lib")
    add_packages("tbox","opencv")
